### ISSUE TITLE
Client id scheme "redirect_uri" used with signed request object

### ISSUE THREAD

**Issue by astrom-b** [EWC-consortium/ewc-wallet-conformance-backend#12]
Hi,

In utils/cryptoUtils.js the function `buildVpRequestJwt` sets up a signed JWT request object with a client id scheme of "redirect_uri". This is not allowed according to the standard.

From OpenID4VP draft 20:
> redirect_uri: This value indicates that the Verifier's redirect URI is also the value of the Client Identifier. In this case, the Authorization Request MUST NOT be signed

**Comment by endimion** [comment]
Hey sorry for getting so long to get to this. This [pull request](https://github.com/EWC-consortium/ewc-wallet-conformance-backend/pull/13) should fix it. However, I think it is best not to merge until after pilots are completed (just so we are certain nothing breaks)

**Comment by lalc** [comment]
Shouldn't really be an issue to merge.

Remember that the phase 01 pilot is based on release 1.0 which was formally released via GitHub earlier.

**Comment by lalc** [comment]
Next time we can formally release it similar to how we did for RFCs. This way, implementors can always adopt a compatible release. Also we needn't wait for correction merges.

**Comment by astrom-b** [comment]
@endimion The proposed fix in the "issue#12" branch doesn't completely fix the problem because the `request` parameter is still present. I get the following:

```http://localhost:8080?state=undefined&client_id=abc&redirect_uri=http://localhost:3000/direct_post_vci&response_type=id_token&response_mode=direct_post&scope=openid&nonce=undefined&request=[object%20Object]
```

Observe that the `request` param has the value `[object Object]`.

**Comment by astrom-b** [comment]
Another thing to note here is that the `response_uri` for `direct_post` is mistakenly set in the `redirect_uri` parameter. Should I report this separately?

**Comment by endimion** [comment]
hey this should be fixed in the staging branch... iff you have the chance please verify and close the issue :)
